//dependencyResolutionManagement {
//    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
//    repositories {
//        google()
//        mavenCentral()
//        jcenter() // Warning: this repository is going to shut down soon
//    }
//}
rootProject.name = "BlackHole"
include ':app'
include ':lib_core'
include ':lib_aop'
include ':lib_gallery'
include ':lib_logcat'
include ':module_music'
include ':module_greenstar'
include ':module_map'

include ':lib_zxing'
include ':lib_updater'
